<a href="https://colab.research.google.com/github/asegura4488/MetodosComputacionales1/blob/main/Semana6/Cuadratura.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import sympy as sym
import math
sym.init_printing(use_unicode=True)

In [2]:
x = sym.Symbol('x', real=True)
f = sym.sin(x)

In [3]:
sym.integrate(f,(x,-1,1))

0

In [4]:
# Integral por cuadratura
w0 = np.array([1.,1.])
r0 = np.array([-1/np.sqrt(3),1/np.sqrt(3)])
r0

array([-0.57735027,  0.57735027])

In [5]:
I = np.sum( w0*np.sin(r0) )
I

0.0

In [6]:
f = sym.exp(-x**2)
f

   2
 -x 
ℯ   

In [7]:
sym.integrate(f,(x,-1,1))

√π⋅erf(1)

In [8]:
f = lambda x: np.exp(-x**2)
I = np.sum( w0*f(r0) )
I

1.4330626211475783

In [9]:
Roots, Weights = np.polynomial.legendre.leggauss(10)
Roots

array([-0.97390653, -0.86506337, -0.67940957, -0.43339539, -0.14887434,
        0.14887434,  0.43339539,  0.67940957,  0.86506337,  0.97390653])

In [10]:
Weights

array([0.06667134, 0.14945135, 0.21908636, 0.26926672, 0.29552422,
       0.29552422, 0.26926672, 0.21908636, 0.14945135, 0.06667134])

In [11]:
I = np.sum( Weights*f(Roots) )
I

1.4936482656243506

In [13]:
a = 0
b = 10
t = 0.5*( Roots*(b-a) + a + b )
I = 0.5*(b-a)*np.sum( Weights*f(t) )
I

0.8860575805791066

In [14]:
x = sym.Symbol('x',real=True)
y = sym.Symbol('y',real=True)

In [17]:
def GetLegendre(n,x,y):

  y = (x**2 - 1)**n

  poly = sym.diff(y,x,n)/(2**n * math.factorial(n))

  return poly

In [55]:
n = 12
Legendre = []
DLegendre = []

for i in range(n-1):
  Poly = GetLegendre(i,x,y)
  Legendre.append(Poly)
  DLegendre.append(sym.diff(Poly,x))

In [56]:
Legendre

⎡                                                                2    ⎛                            ↪
⎢         2        ⎛   2    ⎞     4       2 ⎛ 2    ⎞     ⎛ 2    ⎞     ⎜   4       2 ⎛ 2    ⎞       ↪
⎢      3⋅x  - 1  x⋅⎝5⋅x  - 3⎠  8⋅x  + 24⋅x ⋅⎝x  - 1⎠ + 3⋅⎝x  - 1⎠   x⋅⎝8⋅x  + 40⋅x ⋅⎝x  - 1⎠ + 15⋅ ↪
⎢1, x, ────────, ────────────, ───────────────────────────────────, ────────────────────────────── ↪
⎣         2           2                         8                                      8           ↪

↪         2⎞                                          2             3    ⎛                         ↪
↪ ⎛ 2    ⎞ ⎟      6        4 ⎛ 2    ⎞       2 ⎛ 2    ⎞      ⎛ 2    ⎞     ⎜    6        4 ⎛ 2    ⎞  ↪
↪ ⎝x  - 1⎠ ⎠  16⋅x  + 120⋅x ⋅⎝x  - 1⎠ + 90⋅x ⋅⎝x  - 1⎠  + 5⋅⎝x  - 1⎠   x⋅⎝16⋅x  + 168⋅x ⋅⎝x  - 1⎠  ↪
↪ ──────────, ───────────────────────────────────────────────────────, ─────────────────────────── ↪
↪                                       16                                                

In [57]:
DLegendre

⎡                                                                                                  ↪
⎢               2                   ⎛ 2    ⎞                         ⎛     3         ⎛ 2    ⎞⎞     ↪
⎢           15⋅x    3      3   15⋅x⋅⎝x  - 1⎠   4      2 ⎛ 2    ⎞   x⋅⎝112⋅x  + 140⋅x⋅⎝x  - 1⎠⎠   1 ↪
⎢0, 1, 3⋅x, ───── - ─, 10⋅x  + ─────────────, x  + 5⋅x ⋅⎝x  - 1⎠ + ─────────────────────────── + ─ ↪
⎣             2     2                2                                          8                  ↪

↪           2                                          2                                       2   ↪
↪   ⎛ 2    ⎞                3 ⎛ 2    ⎞         ⎛ 2    ⎞            4 ⎛ 2    ⎞        2 ⎛ 2    ⎞    ↪
↪ 5⋅⎝x  - 1⎠       5   105⋅x ⋅⎝x  - 1⎠   105⋅x⋅⎝x  - 1⎠    6   21⋅x ⋅⎝x  - 1⎠   105⋅x ⋅⎝x  - 1⎠    ↪
↪ ───────────, 21⋅x  + ─────────────── + ───────────────, x  + ────────────── + ──────────────── + ↪
↪     8                       2                 8                    2                 8  

In [58]:
def GetNewtonMethod(f,df,xn,itmax=100,precision=1e-14):

  error = 1
  it = 0

  while error > precision and it < itmax:

    try:
      dfxn = df(xn)
      if np.abs(dfxn) < 1e-16:
        return False

      xn1 = xn - f(xn)/dfxn
      error = np.abs(xn1-xn)
    except ZeroDivisionError:
      print('Division por error')
      return False

    xn = xn1
    it += 1

  if it == itmax:
    return False
  else:
    return xn

In [59]:
def GetRoots(f, df, x, atol=1e-9, max_iter = 100, precision = 1e-14):

  Roots = np.array([])

  for x0 in x:
    #print(x)
    root = GetNewtonMethod(f,df,x0,max_iter,precision)
    #print(x0)
    if root is not False:

      if not any(np.isclose(root, r, atol=atol) for r in Roots):
        print('New root found', root)
        Roots = np.append(Roots,root)

  Roots.sort()

  return Roots

In [60]:
def GetAllRoots(n,xn,Legendre,DLegendre):

  poly = sym.lambdify([x],Legendre[n],'numpy')
  Dpoly = sym.lambdify([x],DLegendre[n],'numpy')
  Roots = GetRoots(poly,Dpoly,xn)

  return Roots


In [61]:
xn = np.linspace(-1,1,100,dtype=np.float32)
Roots = GetAllRoots(10,xn,Legendre,DLegendre)

New root found -0.9739065285171717
New root found -0.8650633666889845
New root found -0.14887433898163122
New root found -0.6794095682990243
New root found 0.14887433898163122
New root found -0.4333953941292471
New root found 0.9739065285171717
New root found 0.8650633666889845
New root found 0.6794095682990243
New root found 0.43339539412924727


In [62]:
Roots, Weights = np.polynomial.legendre.leggauss(10)
Roots

array([-0.97390653, -0.86506337, -0.67940957, -0.43339539, -0.14887434,
        0.14887434,  0.43339539,  0.67940957,  0.86506337,  0.97390653])

In [63]:
Weights

array([0.06667134, 0.14945135, 0.21908636, 0.26926672, 0.29552422,
       0.29552422, 0.26926672, 0.21908636, 0.14945135, 0.06667134])

In [66]:
def GetWeights(Roots,DLegendre):

  Dpoly = sym.lambdify([x],DLegendre[10],'numpy')
  Weights = 2/((1-Roots**2)*Dpoly(Roots)**2)
  return Weights


In [67]:
Weights1 = GetWeights(Roots,DLegendre)

In [68]:
Weights

array([0.06667134, 0.14945135, 0.21908636, 0.26926672, 0.29552422,
       0.29552422, 0.26926672, 0.21908636, 0.14945135, 0.06667134])

In [69]:
Weights1

array([0.06667134, 0.14945135, 0.21908636, 0.26926672, 0.29552422,
       0.29552422, 0.26926672, 0.21908636, 0.14945135, 0.06667134])

In [70]:
x = sym.Symbol('x',real=True)
y = sym.Symbol('y',real=True)

In [71]:
F = x*y*sym.sin(x)
F

x⋅y⋅sin(x)

In [72]:
sym.integrate(F,(x,-1,1),(y,(-1,1)))

0