<a href="https://colab.research.google.com/github/asegura4488/MetodosComputacionales1/blob/main/Semana6/Cuadratura.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import sympy as sym
import math
sym.init_printing(use_unicode=True)

In [2]:
x = sym.Symbol('x', real=True)
f = sym.sin(x)

In [3]:
sym.integrate(f,(x,-1,1))

0

In [4]:
# Integral por cuadratura
w0 = np.array([1.,1.])
r0 = np.array([-1/np.sqrt(3),1/np.sqrt(3)])
r0

array([-0.57735027,  0.57735027])

In [5]:
I = np.sum( w0*np.sin(r0) )
I

0.0

In [6]:
f = sym.exp(-x**2)
f

   2
 -x 
ℯ   

In [7]:
sym.integrate(f,(x,-1,1))

√π⋅erf(1)

In [8]:
f = lambda x: np.exp(-x**2)
I = np.sum( w0*f(r0) )
I

1.4330626211475783

In [9]:
Roots, Weights = np.polynomial.legendre.leggauss(10)
Roots

array([-0.97390653, -0.86506337, -0.67940957, -0.43339539, -0.14887434,
        0.14887434,  0.43339539,  0.67940957,  0.86506337,  0.97390653])

In [10]:
Weights

array([0.06667134, 0.14945135, 0.21908636, 0.26926672, 0.29552422,
       0.29552422, 0.26926672, 0.21908636, 0.14945135, 0.06667134])

In [11]:
I = np.sum( Weights*f(Roots) )
I

1.4936482656243506

In [13]:
a = 0
b = 10
t = 0.5*( Roots*(b-a) + a + b )
I = 0.5*(b-a)*np.sum( Weights*f(t) )
I

0.8860575805791066

In [14]:
x = sym.Symbol('x',real=True)
y = sym.Symbol('y',real=True)

In [17]:
def GetLegendre(n,x,y):

  y = (x**2 - 1)**n

  poly = sym.diff(y,x,n)/(2**n * math.factorial(n))

  return poly

In [21]:
n = 4
Legendre = []
DLegendre = []

for i in range(n):
  Poly = GetLegendre(i,x,y)
  Legendre.append(Poly)
  DLegendre.append(sym.diff(Poly,x))

In [22]:
Legendre

⎡         2        ⎛   2    ⎞⎤
⎢      3⋅x  - 1  x⋅⎝5⋅x  - 3⎠⎥
⎢1, x, ────────, ────────────⎥
⎣         2           2      ⎦

In [23]:
DLegendre

⎡               2    ⎤
⎢           15⋅x    3⎥
⎢0, 1, 3⋅x, ───── - ─⎥
⎣             2     2⎦

In [ ]:
def GetNewtonMethod(f,df,xn,itmax=100,precision=1e-14):

  error = 1
  it = 0

  while error > precision and it < itmax:

    try:
      dfxn = df(xn)
      if np.abs(dfxn) < 1e-16:
        return False

      xn1 = xn - f(xn)/dfxn
      error = np.abs(xn1-xn)
    except ZeroDivisionError:
      print('Division por error')
      return False

    xn = xn1
    it += 1

  if it == itmax:
    return False
  else:
    return xn

In [ ]:
def GetAllRoots(f, df, x, atol=1e-9, max_iter = 100, precision = 1e-14):

  Roots = np.array([])

  for x0 in x:
    #print(x)
    root = GetNewtonMethod(f,df,x0,max_iter,precision)
    #print(x0)
    if root is not False:

      if not any(np.isclose(root, r, atol=atol) for r in Roots):
        print('New root found', root)
        Roots = np.append(Roots,root)

  Roots.sort()

  return Roots