<a href="https://colab.research.google.com/github/asegura4488/MetodosComputacionales1/blob/main/Semana6/DescensoPotencial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
def norm(x, y, z, xi, yi, zi):
  return np.sqrt((x - xi)**2 + (y - yi)**2 + (z - zi)**2)

In [ ]:
def fn(x, y, z):
  return (1 / norm(x, y, z, 1, 0, 0)) + (1 / norm(x, y, z, 0, 2, 0)) + (1 / norm(x, y, z, 0, 0, -1)) + (1 / norm(x, y, z, 0, 0, 4))

In [ ]:
Dx = lambda x, y, z, h=1e-5: (fn(x + h, y, z) - fn(x - h, y, z)) / (2 * h)
Dy = lambda x, y, z, h=1e-5: (fn(x, y + h, z) - fn(x, y - h, z)) / (2 * h)
Dz = lambda x, y, z, h=1e-5: (fn(x, y, z + h) - fn(x, y, z - h)) / (2 * h)

In [ ]:
  x = np.linspace(-2,2,50)
  y = np.linspace(-2,2,50)
  z = np.linspace(-2,2,50)

In [ ]:
gradient = lambda x, y, z: np.array([Dx(x, y, z), Dy(x, y, z), Dz(x, y, z)])

In [ ]:
def gradient_descent(f, epochs=50, gamma=0.1):
  r = [np.random.uniform(-10, 10), np.random.uniform(-10, 10), np.random.uniform(-10, 10)]
  for e in range(epochs):
    fp = gradient(r[0],r[1], r[2])
    r = r - gamma* fp
    print(r)

In [ ]:
gradient_descent(fn)

[-7.07385011 -9.4000497  -0.23133726]
[-7.0753607  -9.40207002 -0.23152861]
[-7.07687069 -9.40408954 -0.23171988]
[-7.07838009 -9.40610826 -0.23191109]
[-7.07988888 -9.40812619 -0.23210223]
[-7.08139708 -9.41014332 -0.2322933 ]
[-7.08290468 -9.41215966 -0.2324843 ]
[-7.08441169 -9.41417521 -0.23267523]
[-7.0859181  -9.41618996 -0.23286609]
[-7.08742392 -9.41820392 -0.23305688]
[-7.08892914 -9.42021709 -0.2332476 ]
[-7.09043377 -9.42222947 -0.23343825]
[-7.0919378  -9.42424106 -0.23362883]
[-7.09344125 -9.42625187 -0.23381935]
[-7.0949441  -9.42826188 -0.23400979]
[-7.09644636 -9.43027111 -0.23420016]
[-7.09794803 -9.43227955 -0.23439047]
[-7.09944911 -9.43428721 -0.2345807 ]
[-7.1009496  -9.43629408 -0.23477087]
[-7.1024495  -9.43830017 -0.23496096]
[-7.10394881 -9.44030547 -0.23515099]
[-7.10544754 -9.44231    -0.23534095]
[-7.10694567 -9.44431374 -0.23553084]
[-7.10844322 -9.4463167  -0.23572066]
[-7.10994019 -9.44831887 -0.23591041]
[-7.11143657 -9.45032027 -0.23610009]
[-7.11293236