<a href="https://colab.research.google.com/github/asegura4488/MetodosComputacionales1/blob/main/Semana8/GausJordan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
A = np.array([[3,-1,-1],[-1.,3.,1.],[2,1,4]])
b = np.array([1.,3.,7.])

In [ ]:
A

array([[ 3., -1., -1.],
       [-1.,  3.,  1.],
       [ 2.,  1.,  4.]])

In [ ]:
def Diagonalizar(A_):

  A = A_.copy()
  n = A.shape[0]

  for i in range(n):

    for j in range(i+1,n):

      a = A[j,i]/A[i,i]
      A[j,:] -= a*A[i,:]

  return A

In [ ]:
Diagonalizar(A)

array([[ 3.        , -1.        , -1.        ],
       [ 0.        ,  2.66666667,  0.66666667],
       [ 0.        ,  0.        ,  4.25      ]])

In [ ]:
def GaussJordan(A_,b_):

  A = A_.copy()
  b = b_.copy()
  n = A.shape[0]

  for i in range(n):
    for j in range(i+1,n):

      a = A[j,i]/A[i,i]
      A[j,:] -= a*A[i,:]
      b[j] -= a*b[i]

  x = np.zeros_like(b)

  for i in reversed(range(n)):

    x[i] = b[i]

    for j in range(i+1,n):
      x[i] -= A[i,j]*x[j]

    x[i] /= A[i,i]


  return x

In [ ]:
x = GaussJordan(A,b)

In [ ]:
x

array([1., 1., 1.])