<a href="https://colab.research.google.com/github/asegura4488/MetodosComputacionales1/blob/main/Semana7/MetodoJacobi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np

In [37]:
A = np.array([[3,-1,-1],[-1,3,1],[2,1,4]])
A

array([[ 3, -1, -1],
       [-1,  3,  1],
       [ 2,  1,  4]])

In [38]:
b = np.array([1.,3.,7.])
b

array([1., 3., 7.])

In [39]:
np.linalg.solve(A,b)

array([1., 1., 1.])

In [40]:
# ALgoritmo de Jacobi

In [41]:
def Jacobi(A,b,x0, itmax = 1000, tolerancia = 1e-16):

  x = x0.copy()

  for it in range(itmax):

    x_new = np.copy(x)

    for i in range(A.shape[0]):

      Suma = 0.
      for j in range(A.shape[1]):
        if i != j:
          Suma += A[i,j]*x[j]
          x_new[i] = (b[i] - Suma)/A[i,i]

    #print(np.linalg.norm( np.dot(A,x_new)-b ))
    if np.linalg.norm( np.dot(A,x_new)-b ) < tolerancia:
      break

    x = np.copy(x_new)

  print(it)

  return x, it

In [42]:
x0 = np.array([0.,0.,0.])
x,_ = Jacobi(A,b,x0)
x

34


array([1., 1., 1.])