<a href="https://colab.research.google.com/github/asegura4488/MetodosComputacionales1/blob/main/Semana7/MetodoJacobi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np

In [11]:
A = np.array([[3,-1,-1],[-1,3,1],[2,1,4]])
A

array([[ 3, -1, -1],
       [-1,  3,  1],
       [ 2,  1,  4]])

In [12]:
b = np.array([1.,3.,7.])
b

array([1., 3., 7.])

In [13]:
np.linalg.solve(A,b)

array([1., 1., 1.])