<a href="https://colab.research.google.com/github/asegura4488/MetodosComputacionales1/blob/main/Semana7/MetodoJacobi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [53]:
import numpy as np

In [54]:
A = np.array([[3,-1,-1],[-1,3,1],[2,1,4]])
A

array([[ 3, -1, -1],
       [-1,  3,  1],
       [ 2,  1,  4]])

In [55]:
b = np.array([1.,3.,7.])
b

array([1., 3., 7.])

In [56]:
np.linalg.solve(A,b)

array([1., 1., 1.])

In [57]:
# ALgoritmo de Jacobi

In [58]:
def Jacobi(A,b,x0, itmax = 1000, tolerancia = 1e-10):

  x = x0.copy()

  for it in range(itmax):

    x_new = np.copy(x)

    for i in range(A.shape[0]):

      Suma = 0.
      for j in range(A.shape[1]):
        if i != j:
          Suma += A[i,j]*x[j]

      # Calculamos el vector
      x_new[i] = (b[i] - Suma)/A[i,i]

    #print(np.linalg.norm( np.dot(A,x_new)-b ))
    if np.linalg.norm( np.dot(A,x_new)-b ) < tolerancia:
      break

    x = np.copy(x_new)

  print(it)

  return x, it

In [59]:
x0 = np.array([0.,0.,0.])
x,_ = Jacobi(A,b,x0)
x

22


array([1., 1., 1.])

In [60]:
def GaussSeidel(A,b,x0, itmax = 100, tolerancia = 1e-10):

  x = x0.copy()

  for it in range(itmax):

    # Hacemos una copia del vector x
    x_new = np.copy(x)

    for i in range(A.shape[0]):

      # Contabilizamos la suma del iterador
      Suma = 0.
      for j in range(A.shape[1]):
        if i != j:
          Suma += A[i,j]*x_new[j]
          # La diferencia radica en que ahora la suma es
          # calcula usando x_new recien actualizado
          x_new[i] = (b[i] - Suma)/A[i,i]

    # Criterio de convergencia
    if np.linalg.norm( np.dot(A,x_new)-b) < tolerancia:
      break

    x = np.copy(x_new)

  print(it)

  return x, it

In [61]:
x0 = np.array([0.,0.,0.])
x,_ = GaussSeidel(A,b,x0)
x

17


array([1., 1., 1.])