<a href="https://colab.research.google.com/github/asegura4488/MetodosComputacionales1/blob/main/Semana2/Sesion4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [42]:
import numpy as np

In [43]:
x = np.array(42)
x.shape

()

In [44]:
x.ndim

0

In [45]:
x = np.array([12, 3, 6, 14])
x.shape

(4,)

In [46]:
x.ndim

1

In [47]:
x.T.shape

(4,)

In [48]:
x = np.array([[3,4],[1,2]])
x.shape

(2, 2)

In [49]:
x.ndim

2

In [50]:
x = np.array([
    [[1,2],[3,4],[0,0]],
    [[5,6],[7,8],[0,0]],
    [[4,3],[6,7],[0,0]]
  ])
x.shape

(3, 3, 2)

In [51]:
x[0].reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [0],
       [0]])

In [52]:
x[0].reshape(2,3)#.shape

array([[1, 2, 3],
       [4, 0, 0]])

In [53]:
x.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [0],
       [0],
       [5],
       [6],
       [7],
       [8],
       [0],
       [0],
       [4],
       [3],
       [6],
       [7],
       [0],
       [0]])

In [54]:
np.transpose(x)

array([[[1, 5, 4],
        [3, 7, 6],
        [0, 0, 0]],

       [[2, 6, 3],
        [4, 8, 7],
        [0, 0, 0]]])