<a href="https://colab.research.google.com/github/asegura4488/MetodosComputacionales1/blob/main/Semana2/Sesion3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np
a = lambda n: 1/n

In [13]:
a(4)

0.25

In [14]:
epsilon = 1e-10

In [15]:
diff = 4
n = 1
while diff > epsilon:
    an = a(n)
    am = a(n+1)
   # print(an,am)
    diff = np.abs(am-an)
    n += 1
    if diff < epsilon:
        print(n)
        break

100001


In [26]:
# Factoriales
f = [1]*10

for i in range(len(f)):
  #print(i,f[i])
  prod = 1
  for j in range(1,i+1):
    #print(i,j)
    prod *= j
  print('Factorial',prod)
  f[i] = prod

Factorial 1
Factorial 1
Factorial 2
Factorial 6
Factorial 24
Factorial 120
Factorial 720
Factorial 5040
Factorial 40320
Factorial 362880


In [19]:
np.math.factorial(4)

<ipython-input-19-483173804809>:1: DeprecationWarning: `np.math` is a deprecated alias for the standard library `math` module (Deprecated Numpy 1.25). Replace usages of `np.math` with `math`
  np.math.factorial(4)


24

In [32]:
# Numpy
f = np.zeros(12, dtype=int)
for i in range(len(f)):
  #print(i,f[i])
  prod = 1
  for j in range(1,i+1):
    #print(i,j)
    prod *= j
  #print('Factorial',prod)
  f[i] = prod
f

array([       1,        1,        2,        6,       24,      120,
            720,     5040,    40320,   362880,  3628800, 39916800])

In [33]:
A = [[1,2],[3,4]]
A

[[1, 2], [3, 4]]

In [34]:
B = [[1,4],[1,6]]
B

[[1, 4], [1, 6]]

In [37]:
# Algoritmo de multiplicar SIn USAR NUMPY

In [42]:
C = [[0,0],[0,0]]

In [45]:
C[0][0] = A[0][0]*B[0][0] + A[0][1]*B[1][0]
C[0][1] = A[0][0]*B[0][1] + A[0][1]*B[1][1]

In [49]:
for i in range(len(A[0])):
  for j in range(len(A[0])):
    Cij = 0
    for k in range(len(A[0])):
      Cij += A[i][k]*B[k][j]
    C[i][j] = Cij
    print(i,j)

0 0
0 1
1 0
1 1


In [50]:
C

[[3, 16], [7, 36]]

In [52]:
A = np.array(A)
B = np.array(B)
A

array([[1, 2],
       [3, 4]])

In [53]:
B

array([[1, 4],
       [1, 6]])

In [54]:
np.dot(A,B)

array([[ 3, 16],
       [ 7, 36]])

In [55]:
A @ B

array([[ 3, 16],
       [ 7, 36]])

In [56]:
A.T

array([[1, 3],
       [2, 4]])