<a href="https://colab.research.google.com/github/asegura4488/MetodosComputacionales1/blob/main/Semana10/ValoresPropios.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [7]:
A = np.array([[1,2,-1,],[1,0,1],[4,-4,5]])
A

array([[ 1,  2, -1],
       [ 1,  0,  1],
       [ 4, -4,  5]])

In [8]:
valores, vectores = np.linalg.eig(A)
valores

array([3., 2., 1.])

In [9]:
vectores

array([[-0.23570226,  0.43643578,  0.40824829],
       [ 0.23570226, -0.21821789, -0.40824829],
       [ 0.94280904, -0.87287156, -0.81649658]])