<a href="https://colab.research.google.com/github/asegura4488/MetodosComputacionales1/blob/main/Semana10/ValoresPropiosPotencia.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

In [5]:
A = np.array([[1,2,-1,],[1,0,1],[4,-4,5]])
A

array([[ 1,  2, -1],
       [ 1,  0,  1],
       [ 4, -4,  5]])

In [6]:
valores, vectores = np.linalg.eig(A)
valores

array([3., 2., 1.])

In [7]:
vectores

array([[-0.23570226,  0.43643578,  0.40824829],
       [ 0.23570226, -0.21821789, -0.40824829],
       [ 0.94280904, -0.87287156, -0.81649658]])

In [8]:
def EigValue(A, itmax = 1000, tolerancia = 1e-6):

  n = A.shape[0]

  v0 = np.zeros(n)
  v0[0] = 1.
  #print(v0)

  for i in range(itmax):

    vn = A @ v0
    lambda1_new = np.dot(v0,vn)
    vn = vn/np.linalg.norm(vn)

    if np.linalg.norm(vn - v0) < tolerancia:
      break

    v0 = vn
    lambda1 = lambda1_new

  #print(lambda1)

  return lambda1, v0

In [9]:
EigValue(A)

(np.float64(3.00001857910504), array([-0.23569965,  0.23570241,  0.94280966]))

In [10]:
vectores

array([[-0.23570226,  0.43643578,  0.40824829],
       [ 0.23570226, -0.21821789, -0.40824829],
       [ 0.94280904, -0.87287156, -0.81649658]])

In [ ]:
valores

array([3., 2., 1.])

In [ ]:
A

array([[ 1,  2, -1],
       [ 1,  0,  1],
       [ 4, -4,  5]])