<a href="https://colab.research.google.com/github/asegura4488/MetodosComputacionales1/blob/main/Semana10/ValoresPropios.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [31]:
A = np.array([[1,2,-1,],[1,0,1],[4,-4,5]])
A

array([[ 1,  2, -1],
       [ 1,  0,  1],
       [ 4, -4,  5]])

In [32]:
valores, vectores = np.linalg.eig(A)
valores

array([3., 2., 1.])

In [33]:
vectores

array([[-0.23570226,  0.43643578,  0.40824829],
       [ 0.23570226, -0.21821789, -0.40824829],
       [ 0.94280904, -0.87287156, -0.81649658]])

In [38]:
def EigValue(A, itmax = 1000, tolerancia = 1e-6):

  n = A.shape[0]

  v0 = np.zeros(n)
  v0[0] = 1.
  #print(v0)

  for i in range(itmax):

    vn = A @ v0
    lambda1_new = np.dot(v0,vn)
    vn = vn/np.linalg.norm(vn)

    if np.linalg.norm(vn - v0) < tolerancia:
      break

    v0 = vn
    lambda1 = lambda1_new

  #print(lambda1)

  return lambda1, v0

In [39]:
EigValue(A)

(np.float64(3.00001857910504), array([-0.23569965,  0.23570241,  0.94280966]))

In [40]:
vectores

array([[-0.23570226,  0.43643578,  0.40824829],
       [ 0.23570226, -0.21821789, -0.40824829],
       [ 0.94280904, -0.87287156, -0.81649658]])

In [41]:
valores

array([3., 2., 1.])

In [60]:
A

array([[ 1,  2, -1],
       [ 1,  0,  1],
       [ 4, -4,  5]])

In [61]:
# Alejandro sugiere que Q esta relacionada con el espacio columna de A
# Pero el espacio columna no es ortogonal

In [62]:
def GrandSchmith(A):

  n,m = A.shape

  Q = np.zeros((n,m))

  for j in range(m):
    v = A[:,j].copy()
    for i in range(j):
      u = Q[:,i]
      v = v - np.dot(u,v)*u

    norm = np.linalg.norm(v)
    Q[:,j] = v/norm


  return Q

In [65]:
Q = GrandSchmith(A)
Q

array([[ 0.23570226,  0.92026272, -0.31234752],
       [ 0.23570226,  0.25767356,  0.93704257],
       [ 0.94280904, -0.29448407, -0.15617376]])

In [64]:
np.dot(Q[:,1],Q[:,2])

np.float64(3.191891195797325e-16)

In [67]:
np.round(Q.T @ A,2)

array([[ 4.24, -3.3 ,  4.71],
       [ 0.  ,  3.02, -2.14],
       [-0.  ,  0.  ,  0.47]])