<a href="https://colab.research.google.com/github/asegura4488/MetodosComputacionales1/blob/main/Semana10/ValoresPropiosQR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [6]:
A = np.array([[1,2,-1,],[1,0,1],[4,-4,5]])
A

array([[ 1,  2, -1],
       [ 1,  0,  1],
       [ 4, -4,  5]])

In [14]:
valores, vectores = np.linalg.eig(A)

In [8]:
def GrandSchmith(A):

  n,m = A.shape

  Q = np.zeros((n,m))

  for j in range(m):
    v = A[:,j].copy()
    for i in range(j):
      u = Q[:,i]
      v = v - np.dot(u,v)*u

    norm = np.linalg.norm(v)
    Q[:,j] = v/norm


  return Q

In [9]:
Q = GrandSchmith(A)
Q

array([[ 0.23570226,  0.92026272, -0.31234752],
       [ 0.23570226,  0.25767356,  0.93704257],
       [ 0.94280904, -0.29448407, -0.15617376]])

In [10]:
np.round(Q.T @ A,2)

array([[ 4.24, -3.3 ,  4.71],
       [ 0.  ,  3.02, -2.14],
       [-0.  ,  0.  ,  0.47]])

In [11]:
# Miremos el paquete
Q,R = np.linalg.qr(A)

In [13]:
R

array([[-4.24264069,  3.29983165, -4.71404521],
       [ 0.        , -3.01846171,  2.1350095 ],
       [ 0.        ,  0.        ,  0.46852129]])

In [18]:
np.linalg.inv(vectores) @ A @ vectores

array([[ 3.00000000e+00,  0.00000000e+00, -8.88178420e-16],
       [ 3.07277296e-15,  2.00000000e+00, -3.48123786e-15],
       [-1.33226763e-15,  1.33226763e-15,  1.00000000e+00]])

In [ ]:
def Eigen()