<a href="https://colab.research.google.com/github/asegura4488/MetodosComputacionales1/blob/main/Semana10/ValoresPropiosQR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [6]:
A = np.array([[1,2,-1,],[1,0,1],[4,-4,5]])
A

array([[ 1,  2, -1],
       [ 1,  0,  1],
       [ 4, -4,  5]])

In [14]:
valores, vectores = np.linalg.eig(A)

In [8]:
def GrandSchmith(A):

  n,m = A.shape

  Q = np.zeros((n,m))

  for j in range(m):
    v = A[:,j].copy()
    for i in range(j):
      u = Q[:,i]
      v = v - np.dot(u,v)*u

    norm = np.linalg.norm(v)
    Q[:,j] = v/norm


  return Q

In [46]:
Q = GrandSchmith(A)
Q

array([[ 0.23570226,  0.92026272, -0.31234752],
       [ 0.23570226,  0.25767356,  0.93704257],
       [ 0.94280904, -0.29448407, -0.15617376]])

In [10]:
np.round(Q.T @ A,2)

array([[ 4.24, -3.3 ,  4.71],
       [ 0.  ,  3.02, -2.14],
       [-0.  ,  0.  ,  0.47]])

In [11]:
# Miremos el paquete
Q,R = np.linalg.qr(A)

In [45]:
Q

array([[-0.23570226, -0.92026272, -0.31234752],
       [-0.23570226, -0.25767356,  0.93704257],
       [-0.94280904,  0.29448407, -0.15617376]])

In [18]:
np.linalg.inv(vectores) @ A @ vectores

array([[ 3.00000000e+00,  0.00000000e+00, -8.88178420e-16],
       [ 3.07277296e-15,  2.00000000e+00, -3.48123786e-15],
       [-1.33226763e-15,  1.33226763e-15,  1.00000000e+00]])

In [40]:
def Eigen(A, max_iter = 1000, tol = 1e-10):

  Ak = A.copy()

  Q_total = np.eye(A.shape[0])

  it = 0
  while it < max_iter:

    Q, R = np.linalg.qr(Ak)

    Ak = R @ Q

    Q_total = Q_total @ Q

    off_diag = np.sqrt( np.sum( np.tril(Ak, -1)**2 ) )
    if off_diag < tol:
      break

    it += 1

  eigenvalues = np.diag(Ak)
  eigenvectors = Q_total

  return eigenvalues, eigenvectors

In [41]:
valores1, vectores1 = Eigen(A)
vectores1

array([[-2.35702260e-01,  9.71825316e-01, -1.18681278e-15],
       [ 2.35702260e-01,  5.71661950e-02,  9.70142500e-01],
       [ 9.42809042e-01,  2.28664780e-01, -2.42535625e-01]])

In [42]:
vectores

array([[-0.23570226,  0.43643578,  0.40824829],
       [ 0.23570226, -0.21821789, -0.40824829],
       [ 0.94280904, -0.87287156, -0.81649658]])

In [43]:
vectores1[:,0] @ vectores1[:,2]

np.float64(-2.7755575615628914e-16)

In [44]:
for i in range(3):
  v1 = vectores[:,i]
  v2 = vectores1[:,i]
  angle = np.arccos(
      np.clip(np.dot(v1,v2)/(np.linalg.norm(v1)*np.linalg.norm(v2)),-1,1))
  print(np.degrees(angle))

0.0
77.75633216047316
101.42175365896236


In [47]:
101.42 + 77.75

179.17000000000002

In [48]:
# Schur
# Jacobi # No computacional